server.port=5155

#DEV
#salesforce.instance-url=https://sobha-developers--training.sandbox.my.salesforce.com

#PROD
salesforce.instance-url=https://sobha-developers.my.salesforce.com

heroku.base-url=https://customer-mobile-app-prod.herokuapp.com/api

spring.servlet.multipart.enabled=false